vim.cmd.colorscheme("kanagawa")
vim.api.nvim_set_hl(0, "DashboardHeader", {fg = "#658594"})
vim.api.nvim_set_hl(0, "oneb", {fg = "#938AA9"})
vim.api.nvim_set_hl(0, "twob", {fg = "#957FB8"})
vim.api.nvim_set_hl(0, "threeb", {fg = "#7E9CD8"})
vim.api.nvim_set_hl(0, "DashboardProjectTitle", {fg = "#E46876"})
vim.api.nvim_set_hl(0, "DashboardMruTitle", {fg = "#E46876"})
vim.api.nvim_set_hl(0, "DashboardProjectIcon", {fg = "#DCD7BA"})
vim.api.nvim_set_hl(0, "DashboardFiles", {fg = "#DCD7BA"})
